config/routes.rb
StudyHall::Application.routes.draw do

	resources :users
	resources :sessions, :only => [:new, :create, :destroy]
  resources :students
  resources :assignments
  resources :attendances, :only => [:index, :show, :new, :create]
  
  match '/signout',     :to => 'sessions#destroy'
  match '/students',    :to => 'students#index'
  match '/signin',      :to => 'sessions#new'
	match '/signup', 	    :to => 'users#new'
	match '/attendance',  :to => 'pages#attendance'
	match '/newYearPromotion',  :to => 'pages#newYearPromotion'
	match '/forgot_password',  :to => 'users#forgot_password'
	root 							    :to => 'pages#home'
	
   

end

app/models/student.rb
class Student < ActiveRecord::Base
  attr_accessible :name, :instructions, :grade
  has_many :assignments, :dependent => :destroy
  
  validates :name, :presence => true
  validates :grade, :presence => true
    
  default_scope :order => 'students.grade, students.name'
  
  def self.search(search)
    if(search)
      where('upper(name) LIKE upper(?)', "%#{search}%")
    else
      scoped
    end
  end
end

app/controllers/students_controller.rb
class StudentsController < ApplicationController
  before_filter :authenticate, :only => [:create, :destroy]
#  before_filter :authorized_user, :only => :destroy
  
  def new
    @student = Student.new
  end  
  
  def create
    @student = Student.new(params[:student])
    if @student.save
      flash[:success] = "Student created!"
      redirect_to students_path
    else
      flash[:notice] = "Student was not created, something went terribly wrong..."
      render 'new'
    end
  end
    
  def destroy
    Student.find(params[:id]).destroy
    flash[:success] = "Student Record Deleted"
    redirect_to students_path
  end
  
  def index
    @students = Student.search(params[:search])
    @student = Student.new 
  end

  def show
		@student = Student.find_by_id(params[:id])
		@assignment = Assignment.new
		@assignments = Assignment.where(:student_id => @student)
		@active_assignments = @assignments.where("active = ?", true).to_a
		@detention_assignments = @assignments.where("active = ? AND detention = ?", true, true).to_a
		@inactive_assignments = @assignments.where(:active => false).to_a
  end
  
  def update
    @student = Student.find(params[:id])
    if @student.update_attributes(params[:student])
      flash[:success] = "Student updated"
      redirect_to @student
    else
      @title = "Edit student"
      render 'edit'
    end
  end
  
  def edit
    @student = Student.find(params[:id])
  end
  
 
  private
  
    def authorized_user
      @student = Student.find(params[:id])
      redirect_to root_path unless current_user?(@student.user)
    end

end

app/views/students/_students.html.erb
<table class="students">
<% if @students.empty? %>
  <tr><td><h3>No students match search criteria</h3></td></tr>
<% else %>

    <tr>
			<% if current_user.admin? %>
				<th></th>
			<% end %>
      <th>Student</th>
			<th>Grade</th>
      <th>Status</th>
    <% @students.each do |student| %>
      <tr>
				<% if current_user.admin? %>
					<td class="student_grade">
						<%= link_to "Delete", student, :method => :delete, :confirm => "Are you sure?", :title => "Confirm Deletion" %>
					</td>
				<% end %>
        <td class="student_name"><%= link_to student.name, student_path(student) %></td>
				<td class="student_grade"><%=student.grade%></td>
        <td class="student_assn">
          <% if Assignment.where(:student_id => student, :active => true).to_a.empty? %>
            No Assignments
          <% else %>
            Currently assigned to study hall or detention
          <% end %>  
        </td>
      </tr>
    <% end %>

<% end %>
</table>

app/views/students/edit.html.erb
<h3>Update Student Information</h3>
<%= form_for @student do |f| %>
  <%= render 'shared/error_messages', :object => f.object %>
  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name, :size => 26 %><br />
	</div>
	<div class="field">
		<%= f.label :grade %>
		<%= f.text_field :grade, :size => 12 %><br />
	</div>
	<div class="actions">
    <%= f.submit %>
  </div>
<% end %>
<% if current_user.admin? %>
<%= link_to "Delete Student", @student, :method => :delete, :confirm => "Are you sure?", :title => "Confirm Deletion" %>
<% end %>

app/views/students/index.html.erb
<%= form_tag students_path, :method => 'get', :id => "student_search" do %>
	<p>
		Filter by name: 
			<%= text_field_tag :search, params[:search] %>
	</p>
<% end %>
<div id="students"><%= render 'students' %></div>
<% if current_user.admin? %>
<p>
	<table>
	<td>
		<h3>Add a student to the database</h3>
  	<%= render 'shared/student_form'%>
	</td>
	</table>
</p>
<hr />
	<%= link_to "New School Year? - Update Database", '/newYearPromotion', :confirm => "This action will delete all assignments, attendance records, and senior students. It will also move all students up a grade level. This should be done only once! Are you sure you want to do this? Hit 'Cancel' if you have any questions in your head.", :class => "small_red_button round" %>		
<% end %>

app/views/students/index.js.erb
$("#students").html("<%= escape_javascript(render("students")) %>");

app/views/students/new.html.erb
<%= render 'shared/student_form' %>

app/views/students/show.html.erb
<h3><%= @student.name %></h3>
<% if current_user.admin? %>
	<%= link_to "Edit", edit_student_path %> student information
<% end %>
<hr />
<table class="students">
  <tr>
    <td class="assn_form">
		<h3>New Assignment</h3>
		<%= render 'shared/assn_form'%>
    </td>
	<td style="vertical-align: top">
		<% unless @active_assignments.empty? %>
			<h3>Active Assignments</h3>
			<table class="students">
				<tr>
					<th>&nbsp;</th>
					<th>&nbsp;</th>
					<th>Assignment</th>
					<th>Sessions</th>
				</tr>
				<% @active_assignments.each do |assignment| %>
				<tr>
	            	<td class="student_inactivate">
	              		<% if current_user.id == assignment.user_id %>
	                  		<%= link_to "close", assignment, 
	                    		:method => :delete,
	                    		:confirm => "Are you sure you want to close this assignment?",
	                    		:title => assignment.assn %>
	              		<% end %>
	            	</td>
					<td class="student_detention">
						<% if assignment.detention? %>
							D
						<% else %>
							SH
						<% end %>
					</td>
					<td class="student_assn">
	              		<%= link_to assignment.assn, assignment_path(assignment) %><br />
	              			<% if assignment.created_at <= (Time.now - 7.days) %>
	                			<span class="timestamp_red">
	                  				Created <%= time_ago_in_words(assignment.created_at)%> 
	                  				ago<br />
	                			</span>
	                			<span class="timestamp">
	                  				by <%= link_to assignment.user.name, user_path(assignment.user) %>
	                			</span>
	              			<% else %>
	                			<span class="timestamp">
	                  				Created <%= time_ago_in_words(assignment.created_at)%> 
	                  				ago <br />
	                  				by <%= link_to assignment.user.name, user_path(assignment.user) %>
	                			</span>
	              			<% end %>
	            	</td>
	            	<td class="student_sessions">
	              		<ul>
							<% if assignment.mlunch? %><li>Monday during lunch</li><% end %>
							<% if assignment.mafter? %><li>Monday after school</li><% end %>
							<% if assignment.tlunch? %><li>Tuesday during lunch</li><% end %>
							<% if assignment.tafter? %><li>Tuesday after school</li><% end %>
							<% if assignment.wlunch? %><li>Wednesday during lunch</li><% end %>
							<% if assignment.wafter? %><li>Wednesday after school</li><% end %>
							<% if assignment.rlunch? %><li>Thursday during lunch</li><% end %>
							<% if assignment.rafter? %><li>Thursday after school</li><% end %>
							<% if assignment.flunch? %><li>Friday during lunch</li><% end %>
							<% if assignment.fafter? %><li>Friday after school</li><% end %>
						</ul>
	            	</td>
					<% end %>
				</tr>
			</table>
		<% end %>
	</td>
  </tr>
</table>


<% unless @inactive_assignments.empty? %>
	<h3>Closed Assignments</h3>
	<table class="students">
  		<tr>
    		<th>Type</th>
			<th>Assignment</th>
			<th>Teacher</th>
			<th>Date Created</th>
		</tr>
  		<% @inactive_assignments.each do |assignment| %>
    		<tr>
				<td class="student_detention">	
					<% if assignment.detention? %>
						D
					<% else %>
						SH
					<% end %></td>
      			<td class="student_assn"><%= link_to assignment.assn, assignment_path(assignment) %><% if assignment.comment? %> *<% end %></td>
      			<td class="student_name"><%= assignment.user.name %></td>
      			<td class="student_sessions"><%= assignment.created_at.strftime('%d %b %Y') %></td>
    		</tr>      
  		<% end %>
	</table>
<% end %>