config/routes.rb
StudyHall::Application.routes.draw do

	resources :users
	resources :sessions, :only => [:new, :create, :destroy]
  resources :students
  resources :assignments
  resources :attendances, :only => [:index, :show, :new, :create]
  
  match '/signout',     :to => 'sessions#destroy'
  match '/students',    :to => 'students#index'
  match '/signin',      :to => 'sessions#new'
	match '/signup', 	    :to => 'users#new'
	match '/attendance',  :to => 'pages#attendance'
	match '/newYearPromotion',  :to => 'pages#newYearPromotion'
	match '/forgot_password',  :to => 'users#forgot_password'
	root 							    :to => 'pages#home'
	
   

end

app/models/user.rb
require 'digest'
class User < ActiveRecord::Base
  include ActiveModel::Validations
  
  class CodeValidator < ActiveModel::EachValidator
    def validate_each(record, attribute, value)
      record.errors[attribute] << "must match the correct secret code." unless value =~ /\Aeducation/i
    end
  end
  
	attr_accessor :password
  attr_accessible :name, :email, :password, :password_confirmation, :secretcode, :admin
	
  has_many :assignments, :dependent => :destroy
  has_many :attendances, :dependent => :destroy
	
	email_regex = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i

	validates :name, 	:presence => true,
										:length => { :maximum => 50 }
	validates :email, :presence => true,
										:format => { :with => email_regex },
										:uniqueness => { :case_sensitive => false}
	validates :password,	:presence	 		=> true,
												:confirmation => true,
												:length				=> { :within => 6..40 }
  validates :secretcode,  :presence => true, 
                          :code => true

	before_save :encrypt_password
	
	def has_password?(submitted_password)
		encrypted_password == encrypt(submitted_password)		
	end

	def self.authenticate(email, submitted_password)
		user = find_by_email(email)
		return nil if user.nil?
		return user if user.has_password?(submitted_password)
	end
	
	def self.authenticate_with_salt(id, cookie_salt)
	  user = find_by_id(id)
	  (user && user.salt == cookie_salt) ? user : nil
  end
	
	def feed(section)
    if section.nil?
      return Student.all
      #Student.where("user_id = ?", id)  
    else  
	    return Student.where(section => true)
    end
  end
  
  def fetch_students_for_attendance(section)
    if section.nil?
      return Assignment.where(:active => true)
    else
      return Assignment.where(section => true, :active => true)
    end
  end
  
  def fetch_detention_for_attendance(section)
    if section.nil?
      return Assignment.where(:active => true)
    else
#      return Assignment.where("section = ? AND active = ? AND detention = ?", true, true, true)
      return Assignment.where(section => true, :active => true, :detention => true)
    end
  end
  
  def fetch_studyhall_for_attendance(section)
    if section.nil?
      return Assignment.where(:active => true)
    else
#      return Assignment.where("section = ? AND active = ? AND detention = ?", true, true, false)
      return Assignment.where(section => true, :active => true, :detention => false)
    end
  end
  
  
  def convert_section_to_string(section)
    if section.nil?
      return "All Active Participants"
    else
      if section.first == 'm'
        day = 'Monday'
      elsif section.first == 't'        
        day = 'Tuesday'
      elsif section.first == 'w'
        day = 'Wednesday'
      elsif section.first == 'r'
        day = 'Thursday'
      else section.first == 'f'
        day = 'Friday'
      end
      
      if section[1] == 'l'
        time = ' at Lunch'
      else
        time = ' After School'      
      end
      return day + time
      
    end
  end
  
  def fetch_session_now()
    hour = Time.now().hour
    day = Time.now().strftime('%A').first.downcase
    if 10 <= hour && hour <= 14
      session = "lunch"
    else
      session = "after"
    end
    if day == "t"
      if Time.now().strftime('%A') == "Tuesday"
        day = "t"
      else
        day = "r"
      end
    end
    section = day + session
    
    return section 
  end
  
  def get_email_list(list_of_assn_id)
  end    
  
  def send_new_password
    new_pass = self.random_string
    self.password = self.password_confirmation = new_pass
    self.save
    Notifier.send_password(email, new_pass).deliver
  end
  
	def random_string
	  rand(36**10).to_s(36)
  end

	private
		def encrypt_password
			self.salt = make_salt if new_record?
			self.encrypted_password = encrypt(self.password)
		end
		
		def encrypt(string)
			secure_hash("#{salt}-#{string}")
		end
		
		def make_salt
			secure_hash("#{Time.now.utc}--#{self.password}")
		end
		
		def secure_hash(string)
			Digest::SHA2.hexdigest(string)
		end
		
		def reset_password(string)
		  self.encrypted_password = encrypt(string)
	  end
		
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_filter :authenticate, :only => [:index, :edit, :update, :destroy]
  before_filter :correct_user, :only => [:edit, :update]
  before_filter :admin_user, :only => :destroy

  def index
    @users = User.paginate(:page => params[:page])
 		@assignments = Assignment.where(:user_id => @user)
		@active_assignments = @assignments.where(:active => true)
		@inactive_assignments = @assignments.where(:active => false)
  end
  
	def show
		@user = User.find_by_id(params[:id])
		@title = @user.name
		@assignments = Assignment.where(:user_id => @user)
		@active_assignments = @assignments.where(:active => true).to_a
		@inactive_assignments = @assignments.where(:active => false).to_a
	end
	
  def new
    @user = User.new
		@title = "Sign up"
  end
  
  def create
    @user = User.new(params[:user])
    if @user.save
      sign_in @user
      flash[:success] = "Welcome to Study Hall!"
      redirect_to @user
    else
      @title = "Sign up"
      @user.password = ""
      @user.password_confirmation = ""
      render 'new'
    end
  end
  
  def update
    @user = User.find(params[:id])
    if @user.update_attributes(params[:user])
      flash[:success] = "Profile updated"
      redirect_to @user
    else
      @title = "Edit user"
      render 'edit'
    end
  end
  
  def edit
    @title = "Edit user"
  end
  
  def destroy
    User.find(params[:id]).destroy
    flash[:success] = "User destroyed."
    redirect_to users_path
  end
  
  def forgot_password
    if request.post?
      u = User.find_by_email(params[:email])
      if u and u.send_new_password
        flash[:success]  = "A new password has been sent to your email."
        redirect_to signin_path
      else
        flash[:error]  = "The email address you entered is not in the database, please try again."
      end
    end
  end
  
  private

# Moved to app/helpers/sessions_helper.rb   
#    def authenticate
#      deny_access unless signed_in?
#    end
    
    def correct_user
      @user = User.find(params[:id])
      redirect_to(root_path) unless current_user?(@user) || current_user.admin?
    end
    
    def admin_user
      redirect_to(root_path) unless current_user.admin?
    end 
end

app/helpers/users_helper.rb
module UsersHelper
	
	def gravatar_for(user, options = { :size => 50 })
		gravatar_image_tag(user.email.downcase, 
											:alt => user.name,
											:class => 'gravatar',
											:gravatar => options)
		end	
end

app/views/users/edit.html.erb
<h3>Edit Your Information</h3>
<%= form_for @user do |f| %>
  <%= render 'shared/error_messages', :object => f.object %>
  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :email %><br />
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :password %><br />
    <%= f.password_field :password %>
  </div>
  <div class="field">
    <%= f.label :password_confirmation, "Confirmation" %><br />
    <%= f.password_field :password_confirmation %>
  </div>
	<div class="button">
		<%= f.label :admin %>
			<% if current_user.admin? %>	
				<%= f.check_box :admin %>
			<% else %>
				<%= f.check_box :admin, :disabled => true %>
			<% end %>
			<br><br>
	</div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/users/forgot_password.html.erb
<h3>Forgotten password</h3>

<%= form_tag('/forgot_password') %>

Email: <%= text_field_tag "email", '', :size => 30 %><br/><br>

<%= submit_tag 'Email password' %>

app/views/users/index.html.erb
<h3>Teachers</h3>
<table>
<% if current_user.admin? %>
	<th></th>
<% end %>
	<th></th>
	<th># currently in study hall</th>	
<% @users.each do |user| %>
	<tr>
		  <% if current_user.admin? %>
				<td>		
		    <%= link_to "delete", user, :method => :delete, :confirm => "Are you sure?", :title => "Delete #{user.name}" %>
				</td>
		  <% end %>			
		<td>
			  <%= link_to user.name, user %>
		</td>
		<td>	
			<%= user.assignments.where(:user_id => user, :active => true).to_a.count %>
		</td>
	</tr>
<% end %>
</table>

app/views/users/new.html.erb
<% if current_user == nil %>
<h3>Sign up</h3>
<%= form_for(@user) do |f| %>
  <%= render 'shared/error_messages', :object => f.object %>
  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :email %><br /> 
    <%= f.text_field :email %>
  </div>  
  <div class="field">
    <%= f.label :password %><br />
    <%= f.password_field :password %>
  </div>
  <div class="field">
    <%= f.label :password_confirmation, "Confirmation" %><br />
    <%= f.password_field :password_confirmation %>
  </div>
  <div class="field">
    <%= f.label :secretcode, "Secret Code - Ask someone if you don't know..."%><br />
    <%= f.password_field :secretcode %>
  </div>

  <div class="actions">
    <%= f.submit "Sign up" %>
  </div>
<% end %>

<% else %>
<p>
Please <%= link_to "sign out", signout_path %> first.</p>
<% end %>

app/views/users/show.html.erb
<table>
  <tr>
  <td>
    <h3><%= @user.name %></h3> (<%= @user.email%>)
    <% if @user == current_user || current_user.admin? %>
      <%= link_to "edit", edit_user_path%>
      </td>
			<% if @user == current_user %>
      <td style="align-right">
      <%= link_to "Assign a student", students_path, :class => "small_dark_blue_button round" %>
      </td>
			<% end %>
    <% else %>
      </td>
    <% end %>
  </tr>
</table>
<% unless @active_assignments.empty? %>
<hr />
<table class="students">
  <tr><th colspan="4"><h3>Current Study Hall Assignments (<%= @active_assignments.count%>)</h3></th></tr>
  <tr>
    <th>&nbsp;</th>
		<th>&nbsp;</th>
    <th>Student</th>
    <th>Assignment</th>
    <th>Sessions</th>
  </tr>
  <% @active_assignments.each do |assignment| %>
  <tr>    
    <td class="student_inactivate">
      <% if current_user.id == assignment.user_id %>
        <%= link_to "close", assignment, 
                  :method => :delete,
                  :confirm => "Are you sure you want to close this assignment?",
                  :title => assignment.assn %>
      <% end %>
      </td>
			<td class="student_detention"><% if assignment.detention %>D<% else %>SH<% end %></td>
      <td class="student_name"><%= link_to assignment.student.name, student_path(assignment.student) %></td>
      <td class="student_assn"><%= link_to assignment.assn, assignment_path(assignment) %>
        <% if assignment.created_at <= (Time.now - 7.days) %>
        <span class="timestamp_red">
                  Created <%= time_ago_in_words(assignment.created_at)%> 
                  ago<br />
                </span>
              <% else %>
                <span class="timestamp">
                  Created <%= time_ago_in_words(assignment.created_at)%> 
                  ago <br />
                </span>
              <% end %>
      
      </td>
      <td class="student_sessions">
        <ul>
          <% if assignment.mlunch? %><li>Monday during lunch</li><% end %>
          <% if assignment.mafter? %><li>Monday after school</li><% end %>
          <% if assignment.tlunch? %><li>Tuesday during lunch</li><% end %>
          <% if assignment.tafter? %><li>Tuesday after school</li><% end %>
          <% if assignment.wlunch? %><li>Wednesday during lunch</li><% end %>
          <% if assignment.wafter? %><li>Wednesday after school</li><% end %>
          <% if assignment.rlunch? %><li>Thursday during lunch</li><% end %>
          <% if assignment.rafter? %><li>Thursday after school</li><% end %>
          <% if assignment.flunch? %><li>Friday during lunch</li><% end %>
          <% if assignment.fafter? %><li>Friday after school</li><% end %>
        </ul>
      </td>

  </tr>
  <% end %>
</table>
<% end %>

<% unless @inactive_assignments.empty? %>
<table class="students">
  <tr><th colspan="3"><h3>Closed Assignments (<%= @inactive_assignments.count%>)</h3></th></tr> 
  <tr>
    <th>&nbsp;</th>
    <th>Student</th>
    <th>Assignment</th>
    <th>Created</th>
  </tr>
  <% @inactive_assignments.each do |assignment| %>
  <tr>
		<td class="student_detention"><% if assignment.detention %>D<% else %>SH<% end %></td>
    <td class="student_name"><%= link_to assignment.student.name, student_path(assignment.student) %></td>
    <td class="student_assn"><%= link_to assignment.assn, assignment_path(assignment) %><% if assignment.comment? %> *<% end %></td>
    <td class="student_sessions"><%= time_ago_in_words(assignment.created_at) %> ago</td>
  </tr>
  <% end %>
</table>
<% end %>