config/routes.rb
StudyHall::Application.routes.draw do

	resources :users
	resources :sessions, :only => [:new, :create, :destroy]
  resources :students
  resources :assignments
  resources :attendances, :only => [:index, :show, :new, :create]
  
  match '/signout',     :to => 'sessions#destroy'
  match '/students',    :to => 'students#index'
  match '/signin',      :to => 'sessions#new'
	match '/signup', 	    :to => 'users#new'
	match '/attendance',  :to => 'pages#attendance'
	match '/newYearPromotion',  :to => 'pages#newYearPromotion'
	match '/forgot_password',  :to => 'users#forgot_password'
	root 							    :to => 'pages#home'
	
   

end

app/models/user.rb
require 'digest'
class User < ActiveRecord::Base
  include ActiveModel::Validations
  
  class CodeValidator < ActiveModel::EachValidator
    def validate_each(record, attribute, value)
      record.errors[attribute] << "must match the correct secret code." unless value =~ /\Aeducation/i
    end
  end
  
	attr_accessor :password
  attr_accessible :name, :email, :password, :password_confirmation, :secretcode, :admin
	
  has_many :assignments, :dependent => :destroy
  has_many :attendances, :dependent => :destroy
	
	email_regex = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i

	validates :name, 	:presence => true,
										:length => { :maximum => 50 }
	validates :email, :presence => true,
										:format => { :with => email_regex },
										:uniqueness => { :case_sensitive => false}
	validates :password,	:presence	 		=> true,
												:confirmation => true,
												:length				=> { :within => 6..40 }
  validates :secretcode,  :presence => true, 
                          :code => true

	before_save :encrypt_password
	
	def has_password?(submitted_password)
		encrypted_password == encrypt(submitted_password)		
	end

	def self.authenticate(email, submitted_password)
		user = find_by_email(email)
		return nil if user.nil?
		return user if user.has_password?(submitted_password)
	end
	
	def self.authenticate_with_salt(id, cookie_salt)
	  user = find_by_id(id)
	  (user && user.salt == cookie_salt) ? user : nil
  end
	
	def feed(section)
    if section.nil?
      return Student.all
      #Student.where("user_id = ?", id)  
    else  
	    return Student.where(section => true)
    end
  end
  
  def fetch_students_for_attendance(section)
    if section.nil?
      return Assignment.where(:active => true)
    else
      return Assignment.where(section => true, :active => true)
    end
  end
  
  def fetch_detention_for_attendance(section)
    if section.nil?
      return Assignment.where(:active => true)
    else
#      return Assignment.where("section = ? AND active = ? AND detention = ?", true, true, true)
      return Assignment.where(section => true, :active => true, :detention => true)
    end
  end
  
  def fetch_studyhall_for_attendance(section)
    if section.nil?
      return Assignment.where(:active => true)
    else
#      return Assignment.where("section = ? AND active = ? AND detention = ?", true, true, false)
      return Assignment.where(section => true, :active => true, :detention => false)
    end
  end
  
  
  def convert_section_to_string(section)
    if section.nil?
      return "All Active Participants"
    else
      if section.first == 'm'
        day = 'Monday'
      elsif section.first == 't'        
        day = 'Tuesday'
      elsif section.first == 'w'
        day = 'Wednesday'
      elsif section.first == 'r'
        day = 'Thursday'
      else section.first == 'f'
        day = 'Friday'
      end
      
      if section[1] == 'l'
        time = ' at Lunch'
      else
        time = ' After School'      
      end
      return day + time
      
    end
  end
  
  def fetch_session_now()
    hour = Time.now().hour
    day = Time.now().strftime('%A').first.downcase
    if 10 <= hour && hour <= 14
      session = "lunch"
    else
      session = "after"
    end
    if day == "t"
      if Time.now().strftime('%A') == "Tuesday"
        day = "t"
      else
        day = "r"
      end
    end
    section = day + session
    
    return section 
  end
  
  def get_email_list(list_of_assn_id)
  end    
  
  def send_new_password
    new_pass = self.random_string
    self.password = self.password_confirmation = new_pass
    self.save
    Notifier.send_password(email, new_pass).deliver
  end
  
	def random_string
	  rand(36**10).to_s(36)
  end

	private
		def encrypt_password
			self.salt = make_salt if new_record?
			self.encrypted_password = encrypt(self.password)
		end
		
		def encrypt(string)
			secure_hash("#{salt}-#{string}")
		end
		
		def make_salt
			secure_hash("#{Time.now.utc}--#{self.password}")
		end
		
		def secure_hash(string)
			Digest::SHA2.hexdigest(string)
		end
		
		def reset_password(string)
		  self.encrypted_password = encrypt(string)
	  end
		
end

app/views/pages/attendance.html.erb
<h3>Attendance - <%= link_to "records", attendances_path %></h3>
<%= render 'shared/attendance_form'%>
<hr />
<p>
<%=  %>
</p>
<% unless params[:attendance_list].blank? %>
	<% if @attendance_list.any? %>
	  <h3><%= @session_in_words %></h3>
	  <table class="students">
	    <tr>
	      <th>Absent?</th>
		    <th>Type</th>
	      <th>Student</th>
	      <th>Teacher</th>
	      <th>Assignment</th>
		  <th>Created</th>
	    </tr>
	    <%= form_tag('/attendances') do %>
	      <%= hidden_field(:user_id, current_user.id )%>
	      <%= hidden_field(:section, @session_in_words )%>
	      <% @attendance_ids.each do |id| %>
	        <%= hidden_field_tag('all_ids[]', id )%>
	      <% end %>
	      <% @attendance_list.each do |assignment| %>
	        <tr>
	          <td class="student_inactivate"><%= check_box_tag('missingstudents[]', assignment.id) %></td>
	          <td class="student_detention"><% if assignment.detention %>D<% else %>SH<% end %></td>
			 			<td class="student_name"><%= link_to assignment.student.name, student_path(assignment.student) %></td>
	          <td class="student_name"><%= assignment.user.name %></td>
	          <td class="student_assn"><%= link_to assignment.assn, assignment_path(assignment) %></td>
        	  <td class="student_sessions"><span class="timestamp"><%= assignment.created_at.strftime('%d %b %Y') %></span></td>
	        </tr>
	      <% end %>
	  </table>
      <%= submit_tag("Send Attendance") %>
    <% end %>
	
	<% else %>
		<h3>No students for this session, send the attendance and go!</h3>
		<%= form_tag('/attendances') do %>
		  <%= hidden_field(:user_id, current_user.id )%>
		  <%= hidden_field(:section, @session_in_words )%>
		<%= submit_tag("Send Attendance") %>
		<% end %>
	<% end %>
<% end %>

app/views/pages/home.html.erb
<% if signed_in? %>
<table class="frontpage">
  <tr>
    <td><%= link_to "Attendance Form", '/attendance', :class => "small_dark_blue_button round" %></td>
    <td><%= link_to "My Students", user_path(current_user), :class => "small_light_blue_button round" %></td>
  </tr>
</table>


<% else %>
  <div align="center">
  <h2>Academia Cotopaxi After School Manager</h2> 
  </div>
<table class="frontpage">
  <tr>
    <td>  
      <%= link_to "Sign in", signin_path, :class => "small_dark_blue_button round" %>
    </td>
    <td>
      <%= link_to "Sign up here", signup_path, :class => "small_light_blue_button round"%>
    </td>
  </tr>
</table>

<% end %>

app/views/pages/home.js.erb
$("#student_list").html("<%= escape_javascript(render(@user)) %>");