config/routes.rb
StudyHall::Application.routes.draw do

	resources :users
	resources :sessions, :only => [:new, :create, :destroy]
  resources :students
  resources :assignments
  resources :attendances, :only => [:index, :show, :new, :create]
  
  match '/signout',     :to => 'sessions#destroy'
  match '/students',    :to => 'students#index'
  match '/signin',      :to => 'sessions#new'
	match '/signup', 	    :to => 'users#new'
	match '/attendance',  :to => 'pages#attendance'
	match '/newYearPromotion',  :to => 'pages#newYearPromotion'
	match '/forgot_password',  :to => 'users#forgot_password'
	root 							    :to => 'pages#home'
	
   

end

app/views/layouts/_footer.html.erb
<footer>
	<nav class="round">
	  Created by Devin Carlson
	</nav>		
</footer>

app/views/layouts/_header.html.erb
<header class="round">

  <nav class="round">
    <table class="round">
      <tr class="middle">
        <td class="img">
          <%=  link_to logo, root_path %>
        </td>
        
        <td class="links middle right round"><ul>
      		<% if signed_in? %>
        		<li><%= link_to "Attendance", '/attendance' %></li>
        		<li><%= link_to "All Students", students_path %></li>
        		<li><%= link_to "All Assignments", assignments_path %></li>
        		<li><%= link_to "My Assignments", current_user %></li>
        		<li><%= link_to "Sign out", signout_path, :method => :delete %></li>
      		<% else %>
        		<li><%= link_to "Sign in", signin_path %></li>
          <% end %>
      	</ul></td>
        
      </tr>
    </table>
  </nav>
</header>

<!--   	 

       		<% if signed_in? %>
        		<td class="bottom right round"><%= link_to "Teachers", users_path %></td>
        		<td class="bottom right round"><%= link_to "My Students", current_user %></td>
        		<td class="bottom right round"><%= link_to "All Students", students_path %></td>
        		<td class="bottom right round"><%= link_to "All Assignments", assignments_path %></td>
        		<td class="bottom right round"><%= link_to "Sign out", signout_path, :method => :delete %></td>
      		<% else %>
        		<td><%= link_to "Sign in", signin_path %></td>
          <% end %>
      	</td>   
-->

app/views/layouts/_stylesheets.html.erb
<!--[if lt IE 9]>
<script src="http://html5shiv.googlecode.com/svn/trunk/html5.js"></script>
<![endif]-->
<%= stylesheet_link_tag 'blueprint/screen', :media => 'screen' %>
<%= stylesheet_link_tag 'blueprint/print', :media => 'print' %>
<%= stylesheet_link_tag 'custom', :media => 'screen' %>
<!--[if lt IE 8]><%= stylesheet_link_tag 'blueprint/ie' %><![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= title %></title>
		<%= csrf_meta_tag %>
		<%= render 'layouts/stylesheets' %>
    <%= javascript_include_tag :defaults %>
    <script type='text/javascript' src='/javascripts/hintvalue/hintvalue.js'></script>
  </head>
  <body>
  	<div class="container">
  	  <div id="header">
			<%= render 'layouts/header' %>
			</div>
			
      <section class="round">
        <% flash.each do |key, value| %>
          <%= content_tag(:div, value, :class => "flash #{key}" )%>
        <% end %>
        <%= yield %>
  		</section>


			<% if Rails.env.development? %>
        <% if current_user.nil?%>
          No Session Data
        <% else %>
          <%= current_user.name %> - Current User
        <% end %>
        <%= debug(params) %>
      <% end %>
  	</div>
  </body>
 </html>